config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'prototypes#index'

  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do
    #表示は投稿画面で表示させる
    resources :comments, only: :create 
  end
  #User情報の詳細のみを表示させるので
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prototype 

  validates :content, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title,presence: true
  validates :catch_copy,presence: true
  validates :concept,presence: true
  validates :image,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true
  
  has_many :prototypes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :users_infomation_save, if: :devise_controller?

  private
  def users_infomation_save
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile,:occupation,:position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    #コメントの新規作成
    @comment = Comment.new(comment_params)
    #コメントを保存
    if @comment.save
      #コメントを現在見ている投稿に付与する
      redirect_to prototype_path(@comment.prototype)
    else
      #保存に失敗したらコメントを投稿しようとした投稿への参照を入れる
      #prototypes/showで詳細画面でコメントを表示させるようにするため
      @prototype = @comment.prototype
      #投稿へのコメントを全て表示させる
      @comments = @prototype.comments
      #詳細ページへ
      render "prototypes/show"
    end
  end

  private
  #コメントの作成・コメントデータベースにコメントを追加・ユーザーidと投稿
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id,prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, except: [:index, :new, :create]
  #編集・更新・削除のみこの関数を呼ぶ
  #投稿した人以外が編集したり削除したりできないようにする
  #編集と削除のアクションと更新処理ができないようにしている
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]
  #ユーザーがログインしていなかった場合、ログインページへ移る
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @prototype = Prototype.all
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if  @prototype.save
      #レスポンスが別のlocation(場所)にリダイレクトされなければならない
      #HTTP POSTリクエストの終わりにリダイレクトが必要だ
      #Error: Form responses must redirect to another location
      #全体表示画面に戻る
      redirect_to root_path
    else
      #エラーが出る状態ならnewに戻る
      render :new,status: :unprocessable_entity
    end
  end

  def show
    #コメントが新規作成できるようにする
    @comment = Comment.new
    #複数個のコメントを取得・表示する
    #プロトタイプ(投稿)を経由するので
    @comments = @prototype.comments
  end

  def edit
  end

  def update
    #更新できたかどうかをif文で判定・更新もストロングパラメータを使用
    if @prototype.update(prototype_params)
      redirect_to prototype_path(@prototype)
    else
      render :edit,status: :unprocessable_entity
    end
  end

  def destroy
    #投稿の削除処理を実行
     if @prototype.destroy
       #全体表示画面に戻る
       redirect_to root_path
     else
       redirect_to root_path
     end
  end

  private

  def prototype_params
    #このユーザーに関連するものをフィルタリング
    #このユーザーですよ〜としていないと「誰の投稿！？」となってエラーになっていた模様
    params.require(:prototype).permit(:title, :catch_copy,:concept,:image).merge(user_id: current_user.id)
  end

  def set_prototype
    #それぞれの処理をする際に必要となる「どの投稿なのか」を取得している
    @prototype = Prototype.find(params[:id])
  end

  #投稿したユーザー以外が削除ボタンなどを押してしまってもその挙動をしないように設定
  def contributor_confirmation
    redirect_to root_path unless current_user == @prototype.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    #表示させるユーザーの情報を取得
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete },class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div> 
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <% else %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%# cssではクラスでスタイリングしているためidなどは不要 %>
<%= form_with model: prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%# プロトタイプに入れたデータを表示させる= %>
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype)%>
  <div class="card__body">
    <%= link_to prototype.title, prototype_path(prototype), class: :card__title%>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to "by #{prototype.user.name}", user_path(prototype.user), class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%# locals: { prototype: @prototype }→ここで使えるprototype変数を渡した先のファイル(_form.html.erb)でも@prototype使えるようにしている %>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%# current_user %>
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
    <%# collection: @prototypes→@prototypeにある要素を取得可能 %>
    <div class="card__wrapper">
      <%= render partial: 'prototype', collection: @prototype %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%# locals: { prototype: @prototype }→ここで使えるprototype変数を渡した先のファイル(_form.html.erb)でも@prototype使えるようにしている %>
        <%= render partial: 'form' , locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: :prototype__user %>
      <% if current_user == @prototype.user%>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype), 
          data: { turbo_method: :delete }, class: :prototype__btn %>
        </div>
       <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <% if user_signed_in? %>
          <%# 投稿データだけでなく、その投稿にされたコメントを取得するのでモデルは２つ必要 %>
            <%= form_with model: [@prototype, @comment],local: true do |f|%>
              <div class="field">
                <%= f.label :content, "コメント" %><br />
                <%= f.text_field :content, id:"comment_content" %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %>
          <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する = 保存されているコメントを全部とってくる %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%# コメントをしたユーザーの名前を取得する・ %>
              <%= link_to "（ #{comment.user.name} ）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<%# 間違えてusers関係のファイルを消してしまったためコピペしている %>
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'prototypes/prototype', collection: @user.prototypes %>
      </div>
    </div>
  </div>
</div>